config/routes.rb
Rails.application.routes.draw do
	root 'posts#top'
	devise_for :users
	get 'users/about'
  resources :users,only:[:show,:edit,:update]
  resources :relationships, only:[:create,:destroy]
  resources :posts do
  	resources :comments, only:[:create,:destroy]
    resources :likes,only:[:create,:destroy]
  end
  resources :categories, only:[:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts,dependent: :destroy
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :content, presence: true,length:{ maximum: 100}
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many :likes,dependent: :destroy
	has_many :liked_users, through: :likes, source: :user
	has_many :comments,dependent: :destroy
	attachment :image

	validates :title, presence: true, length: {maximum: 25}
	validates :content, presence: true, length: {maximum: 200}
	validates :rate, presence: true

	def like_user(user_id)
		likes.find_by(user_id: user_id)
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  validates :name, presence: true, length:{ maximum: 10}

  has_many :posts,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :relationships
  has_many :comments,dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

	def after_sign_in_path_for(resource)
  		posts_path
  	end

  def after_sign_out_path_for(resource)
  	root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def create
		category = Category.new(category_params)
		category.save
		redirect_to posts_path
	end

	def destroy
		category = Category.find(params[:id])
		category.delete
		redirect_to posts_path
	end

	private
	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		@comment = post.comments.new(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			flash[:success] = "コメントしました"
			redirect_to post_path(post)
		else
			flash[:alert] = "コメントに失敗しました"
			redirect_to post_path(post)
		end
	end

	def destroy
		post = Post.find(params[:post_id])
		comment = Comment.find(params[:id])
		comment.destroy
		redirect_to post_path(post)
	end

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit,:update,:destroy]

  def top
  end

  PER = 6
  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @posts = @category.posts.page(params[:page]).per(PER).reverse_order
      @categories = Category.all
      @user = current_user
      @post = Post.new
    else
  	 @posts = Post.page(params[:page]).per(PER).reverse_order
  	 @post = Post.new
     @categories = Category.all
     @category = Category.new
     @user = current_user
    end
  end

  def new
  	@post = Post.new
    @category = Category.all
  end

  def create
  	@post = Post.new(post_params)
    @post.user_id = current_user.id
  	if @post.save
      redirect_to post,notice: "投稿しました"
    else
      @categories = Category.all
      @user = current_user
      @posts = Post.page(params[:page]).per(PER).reverse_order
      render 'index'
    end
  end

  def show
  	@post = Post.find(params[:id])
    @user= @post.user
    @comments = @post.comments
    @comment = Comment.new
    @like = Like.new
    @categories = Category.all
  end

  def edit
  	@post = Post.find(params[:id])
    @category = Category.all
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
      redirect_to post_path(post),notice: '更新しました'
    else
      @category = Category.all
      render 'edit'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:title,:content,:rate,:image,:category_id,:user_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:follow_id])
    following = current_user.follow(user)
    if following.save
      redirect_to user,notice:'ユーザーをフォローしました'
    else
      redirect_to user,notice: 'ユーザーのフォローに失敗しました'
    end
  end

  def destroy
    user = User.find(params[:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      redirect_to user,notice:'ユーザーのフォローを解除しました'
    else
      redirect_to user, notice:'ユーザーのフォロー解除に失敗しました'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]

	def about
	end

	PER = 2
	def show
		@user = User.find(params[:id])
		@post = @user.liked_posts.page(params[:page]).per(PER).reverse_order
		@posts = @user.posts.page(params[:page]).per(PER).reverse_order
		@categories = Category.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		redirect_to @user,notice: 'ユーザー情報を更新しました'
		else
		render 'edit'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name,:image,:introduction)
	end

	def correct_user
		user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<div class="comment_new">
	<%= form_for [@post, @comment] do |f| %>
	<div class="comment_new_content">
		<%= f.label :コメント %>
		<%= f.text_area :content %>
	</div>
	<div class="comment_new_btn">
		<%= f.submit 'コメント追加' %>
		<% end %>
	</div>
</div>

app/views/posts/_error_message.html.erb
<% if posts.errors.any? %>
    <div id="error_explanation">
      <h2><%= posts.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% posts.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<%= javascript_include_tag 'jquery.raty' %>

<%= render 'posts/error_message', posts: @post %>
<div class="post__edit-main">
  <div class="post__edit">
	 <%= form_for @post do |f| %>

    <h3 class="post__edit--image">
	   <%= f.label :image %>
	   <%= f.attachment_field :image %>
    </h3>

    <h3 class="post__edit--title">
      <%= f.label :title %>
	   <%= f.text_field :title %>
    </h3>

    <h3 class="post__edit--rate">
	   <div id="star">
      <%= f.label :rate,'評価 ' %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>

    <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'post[rate]',
      half: true,
    });
    </script>
    </h3>

	 <h3 class="post__edit--content">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </h3>

    <h3 class="post__edit--category">
	   <%= f.label :category %>
	   <%= f.collection_select :category_id,@category,:id,:name %>
	 </h3>
    <%= f.submit '投稿' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= javascript_include_tag 'jquery.raty.js' %>

<%= render 'posts/error_message', posts: @post %>
<div class="post__main">

	<div class="post__main-user">
		<% if user_signed_in? %>
		<div class="post__main-user--image">
			<%= attachment_image_tag(@user, :image, :fill, 100,100, fallback: "/images/no_image.jpg") %>
		</div>

		<div class="post__main-user--name">
			Name: <%= link_to @user.name, user_path(@user) %>
		</div>

		<div class="post__main-user--introduction">
			プロフィール:<br>
			<%= @user.introduction %>
		</div>
		<div class="user__show-1--follow">
			フォロー:<%= @user.followings.count %>
			フォロワー:<%= @user.followers.count %>
		</div>

		<% if @user == current_user %>

		<div class="post__main-user--btn">
			<%= link_to '編集',edit_user_path(@user) %> |
			<%= link_to '新規投稿',new_post_path %>
		</div>
	<% end %>
		<% end %>
	</div>

	<div class="post__main-content">
		<% @posts.each do |post| %>
		<div class="post__main-content--body">
			<div class="post__main-content--body_image">
				<%= attachment_image_tag(post, :image, :fill, 50, 50, fallback: "/images/no_image.jpg") %>
			</div>

			<div class="post__main-content--body_title">
				title:<%= link_to post.title,post_path(post) %>
			</div>

			<div class="post__main-content--body_name">
				投稿者:<%= post.user.name %>
			</div>

			<div class="post__main-content--body_rate">
				評価
				<div id="star-rate-<%= post.id %>"></div>
				<script>
					$('#star-rate-<%= post.id %>').raty({
					size: 36,
					starOff:  '<%= asset_path('star-off.png') %>',
					starOn : '<%= asset_path('star-on.png') %>',
					starHalf: '<%= asset_path('star-half.png') %>',
					half: true,
					readOnly: true,
					score: <%= post.rate %>,
					});
				</script>
			</div>
		</div>
		<% end %>
		<div class="post__main-content--body_paginate">
					<%= paginate @posts %>
				</div>
	</div>

	<div class="post__main-category">
		<h2 class="post__main-category--name">
			カテゴリー
		</h2>
		<% @categories.each do |category| %>
		<div class="post__main-category--link">
			<%= link_to category.name, posts_path(category_id: category.id), category_id: category.id %><br>
		</div>
		<% end %>
		<div class="post__main-category--new">
			<%= form_for @category do |f| %>
			<%= f.text_field :name %>
			<%= f.submit '追加' %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<%= javascript_include_tag 'jquery.raty' %>

  <div class="post__new">
	 <%= form_for @post do |f| %>

   <h3 class="post__new--image">
	 <%= f.label :image %>
	 <%= f.attachment_field :image %>
  </h3>

  <h3 class="post__new--title">
	 <%= f.label :title %>
	 <%= f.text_field :title %>
  </h3>

  <h3 class="post__new--rate">
	 <div id="star">
      <%= f.label :rate,'評価 ' %>
      <%= f.hidden_field :rate, id: :review_star %>
    </div>

    <script>
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'post[rate]',
      half: true,
    });
    </script>
  </h3>

  <h3 class="post__new--content">
	 <%= f.label :content %>
	 <%= f.text_area :content %>
  </h3>

  <h3 class="post__new--category">
	 <%= f.label :category %>
	 <%= f.collection_select :category_id,@category,:id,:name %>
  </h3>
  <h3 class="post__new--btn">
	 <%= f.submit '投稿' %>
  </h3>
    <% end %>
  </div>

app/views/posts/show.html.erb
<%= javascript_include_tag 'jquery.raty' %>

<div class="post__show">

	<div class="post__show-1">
		<% if user_signed_in? %>
			<div class="post__main-user--image">
				<%= attachment_image_tag(@user, :image, :fill, 100,100, fallback: "/images/no_image.jpg") %>
			</div>
			<div class="post__main-user--name">
				Name:<%= link_to @user.name, user_path(@user) %>
			</div>

			<div class="post__main-user--introduction">
				プロフィール:<br>
				<%= @user.introduction %>
			</div>
			<div class="user__show-1--follow">
			フォロー:<%= @user.followings.count %>
			フォロワー:<%= @user.followers.count %>
		</div>
			<% if @user == current_user %>
			<div class="post__main-user--btn">
				<%= link_to '編集',edit_user_path(@user) %> |
				<%= link_to '新規投稿',new_post_path %>
			</div>
			<% end %>
		<% end %>
	</div>

	<div class="post__show-2">
		<div class="post__show-2-content">
			<div class="post__show-2--image">
				<%= attachment_image_tag(@post, :image, :fill, 100, 100, fallback: "/images/no_image.jpg") %>
			</div>

			<% if @user == current_user %>
			<div class="post__show-2--btn1">
				<%= link_to '編集',edit_post_path(@post) %>|<%= link_to '削除',@post,method: :delete,data: {confirm: "本当に削除してもよろしいですか？"} %>
			</div>
			<% end %>

			<% if user_signed_in? %>
			<div class="post__show-2--btn2">
				<% if current_user.already_liked?(@post) %>
				<%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
				<% else %>
				<%= button_to 'いいね', post_likes_path(@post) %>
			<% end %>
				<h2>いいねしたユーザー</h2>
				<% @post.liked_users.each do |user| %>
				<li><%= user.name %></li>
				<% end %>
			</div>
			<% end %>
		</div>
	</div>

	<div class="post__show-3">
		<div class="post__show-3--title">
			<h2>Title</h2>
			<%= @post.title %>
		</div>
		<div class="post__show-3--rate">
			<h2>Rate</h2>
			<div id="star-rate-<%= @post.id %>"></div>
			<script>
				$('#star-rate-<%= @post.id %>').raty({
				size: 36,
				starOff:  '<%= asset_path('star-off.png') %>',
				starOn : '<%= asset_path('star-on.png') %>',
				starHalf: '<%= asset_path('star-half.png') %>',
				half: true,
	 		  readOnly: true,
				score: <%= @post.rate %>,
				});
			</script>
		</div>

		<div class="post__show-3--content">
			<h2>Content</h2>
			<%= @post.content %><br>
		</div>

		<% if user_signed_in? %>

		<div class="post__show-3--comment-new">
			<%= render 'comments/new' %>
		</div>
		<% end %>

		<div class="post__show-3--comment-index">
			<h2>コメント一覧</h2>
			<% @comments.each do |comment| %>
			<div class="post__show-3--comment">
			<%= comment.content %>
			[ユーザー名:<%= comment.user.name %>]
			<% if user_signed_in? %>
			<% if @user == comment.user %>
			<%= link_to "削除", post_comment_path(post_id: @post, id: comment.id), method: :delete,data: {confirm: "本当に削除してもよろしいですか？"} %>
			<% end %>
			<% end %>
			</div>
			<% end %>
		</div>
	</div>

	<div class="post__show-4">
		<div class="post__show-4--category">
			<div class="post__show-4--category_name">
				カテゴリー
			</div>
			<% @categories.each do |category| %>
			<div class="post__show-4--category_link">
				<%= link_to category.name, posts_path(category_id: category.id), category_id: category.id %><br>
			</div>
			<% end %>
		</div>
	</div>

</div>

app/views/posts/top.html.erb
<div class="post">
	<div class="post__about-visual">
		</div>
		<div class="post__aboutcontent">
			<div class="post__aboutcontent--1">
				当サイトについて
			</div>
			<div class="post__aboutcontent--2">
				お気に入りや好きなものを共有して繋がろう、<br>
				レビューし合おうをコンセプトにしています<br>
				好きな作品、モノを共有して新しい発見をし、<br>
				今まで好きだったものを、より一層好きになりませんか？
			</div>
		</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_error_message.html.erb
<% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= user.errors.count %>件のエラーが発生しました。</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/_show.html.erb
<div class="user__side">
		<% if user_signed_in? %>
		<div class="user__side--image">
			<%= attachment_image_tag(@user, :image, :fill, 100,100, fallback: "/images/no_image.jpg") %>
		</div>

		<div class="user__side--name">
		Name:  <%= @user.name %>
		</div>
		<br>
		<div class="user__side--introduction">
			プロフィール:<br>
			  <%= @user.introduction %>
		</div>
		<div class="user__side--btn">
			<%= link_to '編集',edit_user_path(@user) %> |

			<%= link_to '新規投稿',new_post_path %>
		</div>
		<% end %>
	</div>

app/views/users/about.html.erb
	<div class="user__about">
		当サイトの使用手順<br>
		　・サインイン後投稿フォームから投稿可能になります。<br>
		　・投稿詳細画面からコメントの投稿を行うことが可能。<br>
		今後実装予定の機能<br>
		　・SNS認証<br>
		　・Ajaxを使用した非同期通信の実装<br>
		　・お問い合わせ機能の追加
	</div>
</div>

app/views/users/edit.html.erb
<%= render 'users/error_message', user: @user %>

<div class="user__main-edit">

	<%= form_for @user do |user| %>

	<h3 class="user__main-edit--image">
		<%= user.label :image %>
		<%= user.attachment_field :image %>
	</h3>

	<h3 class="user__main-edit--name">
	<%= user.label :名前 %>
	<%= user.text_field :name %>
	</h3>

	<h3 class="user__main-edit--int">
	<%= user.label :自己紹介欄 %>
	<%= user.text_area :introduction %>
	</h3>

	<h3 class="user__main-edit--btn">
	<%= user.submit '更新' %>
	<% end %>
	</h3>
</div>

app/views/users/show.html.erb
<%= javascript_include_tag 'jquery.raty.js' %>
<%= render "users/error_message", user: @user %>

<div class="user__show">
	<div class="user__show-1">
		<% if user_signed_in? %>
		<div class="user__show-1--image">
			<%= attachment_image_tag(@user, :image, :fill, 100,100, fallback: "/images/no_image.jpg") %>
		</div>
		<%= render 'relationships/follow_button', user: @user %>
		<div class="user__show-1--name">
			Name:<%= link_to @user.name, user_path(@user) %>
		</div>
		<div class="user__show-1--introduction">
			プロフィール:<br>
			<%= @user.introduction %>
		</div>
		<div class="user__show-1--follow">
			フォロー:<%= @user.followings.count %>
			フォロワー:<%= @user.followers.count %>
		</div>
		<% if @user == current_user %>
		<div class="user__show-1--btn">
			<%= link_to '編集',edit_user_path(@user) %> |

			<%= link_to '新規投稿',new_post_path %>
		</div>
		<% end %>
		<% end %>
	</div>

	<div class="user__show-2">
		<h2>投稿一覧</h2>
		<div class="user__show-post">
			<% @posts.each do |post| %>
			<div class="user__show-posts">
				<div class="user__show-posts--image">
					<%= attachment_image_tag(post, :image, :fill, 50, 50, fallback: "/images/no_image.jpg") %>
				</div>

				<div class="user__show-posts--title">
					title:<%= link_to post.title,post_path(post) %>
				</div>

				<div class="user__show-posts--rate">
					評価
					<div id="star-rate-<%= post.id %>"></div>
					<script>
						$('#star-rate-<%= post.id %>').raty({
						size: 36,
						starOff:  '<%= asset_path('star-off.png') %>',
						starOn : '<%= asset_path('star-on.png') %>',
						starHalf: '<%= asset_path('star-half.png') %>',
						half: true,
						readOnly: true,
						score: <%= post.rate %>,
						});
					</script>
				</div>
			</div>
			<% end %>
			<div class="user__show-posts--paginate">
			<%= paginate @posts %>
		</div>
		</div>
	</div>

	<div class="user__show-3">
		<h2>いいねした投稿</h2>
		<div class="user__show-like">
			<% @post.each do |post| %>
			<div class="user__show-likes">
			<div class="user__show-like--image">
					<%= attachment_image_tag(post, :image, :fill, 50, 50, fallback: "/images/no_image.jpg") %>
			</div>
			<div class="user__show-like--title">
			title:<%= link_to post.title,post %>
			</div>
			<div class="user__show-like--content">
				<%= post.content %>
			</div>
			<div class="user__show-like-user">
				投稿者:<%= post.user.name %>
			</div>
			</div>
		<% end %>
		<div class="user__show-like--paginate">
			<%= paginate @post %>
		</div>
	</div>
	</div>

	<div class="user__show-4">
		<div class="user__show-4--category">
			<h2 class="user__show-4--category_name">
				カテゴリー
			</h2>
			<% @categories.each do |category| %>
			<div class="user__show-4--category_link">
				<%= link_to category.name, posts_path(category_id: category.id), category_id: category.id %><br>
			</div>
			<% end %>
		</div>
	</div>
</div>